[random]
# Perform 4K random reads for 10 seconds using direct I/Os
# when tested on teslino-bambino, this gives 1205usec 99th percentile clat
# the disk there must be slower than MICRON® 2200 PCIe NVMe Client SSD, the official description of which (https://www.micron.com/-/media/client/global/documents/products/product-flyer/2200_pcie_nvme_ssd_product_brief.pdf?la=en) tells about 800mb/s
filename=/dev/vda1
readwrite=randread
blocksize=4k
ioengine=sync
direct=1
time_based=1
runtime=10